### ISSUE TITLE
Overlay77 (J) adding?

### ISSUE THREAD

**Issue by Halfshadow** [pret/pokeheartgold#14]
Hello. Could you please add Overlay77 from (J) version that is the slot machines code? Maybe in the future could you be able to adapt it to works with western releases.

**Comment by luckytyphlosion** [comment]
lol

**Comment by luckytyphlosion** [comment]
(The serious answer is that the project is in a way too infantile state to actually do some complex modification like that. Remember that you can't simply just plop in code from another language and expect it to just work.)

**Comment by Halfshadow** [comment]
Sure, but to begin you could add it and try to disassembly to verify in which way it links to other subroutines outside itself...

However I hope could be planned also if now is too early.
