### ISSUE TITLE
Determine style guide for function naming

### ISSUE THREAD

**Issue by luckytyphlosion** [pret/pokeheartgold#213]
Examples to kick off discussion.

### Example 1
![image](https://github.com/pret/pokeheartgold/assets/10688458/d9e572d5-c8e5-433f-84d3-b65a00f05c6f)

### Example 2
![image](https://github.com/pret/pokeheartgold/assets/10688458/df7c57b5-125b-47d5-8045-1f163828895b)

### Example 3
![image](https://github.com/pret/pokeheartgold/assets/10688458/30710758-9d5c-4aa0-b630-1a8e95093b90)

### Example 4
![image](https://github.com/pret/pokeheartgold/assets/10688458/ba529dae-eddd-4ca0-9536-f0a22722f955)

### Example 5
![image](https://github.com/pret/pokeheartgold/assets/10688458/dd18384a-8c18-45e8-a039-2f6445b1d3d1)

**Comment by AnonymousRandomPerson** [comment]
Explorers of Sky's hacking scene already has symbol names that are widely accepted within that community, and they generally use the no-underscore <verb><noun> convention like `GetEncounterResult`. I don't mind if the proposed style is chosen specifically for HeartGold (although I don't personally like it), but if it's intended to spread into the other pret repos then I feel that will be a losing battle.

**Comment by adrienntindall** [comment]
The reasoning I have for this function naming convention is because the code is trying to pretend like it has classes and class functions by passing struct pointers over and over. Hence, `Encounter_GetResult` is equivalent to if the `Encounter` struct had a `GetResult` function. But this is c. So classes aren't real.

**Comment by AnonymousRandomPerson** [comment]
This feels like pretending that classes are real in a different way, by prefixing the "class name" in front of any functions associated with that "class". `GetResult` is simply a bad function name, and a better name like `GetEncounterResult` would not run into the same issue.

**Comment by adrienntindall** [comment]
Encounter_GetResult and GetEncounterResult read the same to me, except in the first it's immediately obvious that you need to put the encounter struct in as an argument where the second could just be a function that gets it from a FieldSystem or the like. It also helps to differentiate between functions that will get the same variable/have similar functionality but through different structs (ex FieldSystem_GetBattleResult vs BattleSystem_GetBattleResult).

**Comment by adrienntindall** [comment]
The point is the code is written in a way that pretends classes are real, and trying to go against that isn't going to lead to a clean convention

**Comment by AnonymousRandomPerson** [comment]
What happens when two or three structs are passed into a function, or no structs?

**Comment by adrienntindall** [comment]
Use the first one, I really haven't had much issue with this convention so far

**Comment by AnonymousRandomPerson** [comment]
Not really a fan. The first struct is not always more important than the other ones, and there are plenty of cases where this convention would get in the way of a succinctly named function. And this doesn't account for functions where no struct is passed in either.

**Comment by adrienntindall** [comment]
I think that you're thinking about this too much and no naming convention is perfect, the thing is if we don't use it we're going to have way more functions that are poorly named than ones that aren't. Also class functions arent the only functions to exist

**Comment by red031000** [comment]
1. no
2. yes
3. yes
4. no
5. yes

this is mostly making exceptions to save stuff, and changing it would be a lot of work but, if it's wanted I can slowly go through and change save stuff to be a bit better

**Comment by red031000** [comment]
as for `Encounter_GetResult` vs `GetEncounterResult` we have gradually be leaning more towards the former, but there are many examples of the latter still around, as for which one is preferred I don't mind, but for the latter I can see it being awkward in some circumstances

**Comment by AnonymousRandomPerson** [comment]
I can see this helping in specific circumstances, but I don't feel it makes sense to apply this convention as widely as it's being proposed. As mentioned previously, I don't mind if this convention is decided for HeartGold, but I won't be following this convention for Explorers of Sky to avoid breaking their existing widely accepted function names.

**Comment by red031000** [comment]
EOS is a chunsoft game so it's possible (and likely) that things are not done in the same class-esque structure as the main series games

**Comment by PikalaxALT** [comment]
`Save_XXX_Get` was intended to create a uniform naming scheme for the save block functions, as a counterpart to `Save_XXX_sizeof`.
