### ISSUE TITLE
Remove all instances of work terminology.

### ISSUE THREAD

**Issue by luckytyphlosion** [pret/pokeheartgold#216]
Useful grep:
`grep -Pwr --include="*.c" --include="*.h" --exclude-dir="tools" --exclude-dir="sub" --exclude-dir="lib" --exclude-dir=".github" --exclude-dir="files" "(\w+[wW]ork|work)"`

**Rationale:**
> Kurausukun — 05/12/2023 5:46 PM
> Remember that "work" is Japanese code lingo for "temporary/generic variable/memory"
> Kurausukun — 05/12/2023 5:49 PM
> "work" will not mean anything to anyone who doesn't know JP and I think all instances of it should be removed

**Comment by red031000** [comment]
agreed, and todo
