### ISSUE TITLE
Decide consensus on use of `no` as "number"

### ISSUE THREAD

**Issue by luckytyphlosion** [pret/pokeheartgold#217]
Alternative is `num`, `index`, `idx`, probably others depending on context.

**Comment by AnonymousRandomPerson** [comment]
Like with the index/idx thread, I don't feel strongly about enforcing a global convention here in the first place. It often depends on context, as mentioned.

**Comment by red031000** [comment]
imo num rather than no

**Comment by luckytyphlosion** [comment]
> Like with the index/idx thread, I don't feel strongly about enforcing a global convention here in the first place. It often depends on context, as mentioned.

This is more about whether we should allow `no` to mean an ordinal value at all.

**Comment by lhearachel** [comment]
`num`

`no` is an English word. A non-zero number of people *will* confuse it for the word before realizing that it's an abbreviation.

**Comment by PikalaxALT** [comment]
Agree, `num` is more intuitive. Rest in pieces, `monsno`.

**Comment by AsparagusEduardo** [comment]
I also agree with `num`

**Comment by tgsm** [comment]
I'm okay with `no` or `num`. Seems like most people prefer `num`.

**Comment by luckytyphlosion** [comment]
We have reached consensus. `no` is no more.
