### ISSUE TITLE
Decide consensus on `idx` vs `index`

### ISSUE THREAD

**Issue by luckytyphlosion** [pret/pokeheartgold#218]
Self-explanatory.

**Comment by adrienntindall** [comment]
index

**Comment by AnonymousRandomPerson** [comment]
I use `index` but I don't mind either way. It's not something I care that much about enforcing consistency with, but I don't have an issue if others want such a rule.

**Comment by red031000** [comment]
index

**Comment by tgsm** [comment]
index

**Comment by luckytyphlosion** [comment]
tgsm said index, but github thought it was an unhelpful comment. Anyway, the consensus is to use index over idx.

**Comment by AsparagusEduardo** [comment]
sorry I'm late (index)
