### ISSUE TITLE
Decide consensus on naming of unknown static/global variables.

### ISSUE THREAD

**Issue by luckytyphlosion** [pret/pokeheartgold#219]
Please please please let's not decide on `_021D4178` as it is ambiguous with auto-disassembled "anonymous" labels.

Possible candidates are:
- `g021D4178` (shinny notation)
- `gUnk_021D4178` (what was used in the gen 3 decomps. Can omit the underscore)

**Comment by red031000** [comment]
diamond has it just Unk_021D4178 as it can be difficult to determine if it's static or not without further documentation/decompilation (e.g. in asm files), I agree the _021D4178 is stupid

**Comment by red031000** [comment]
I'd rather go with the gen 3 stype

**Comment by AnonymousRandomPerson** [comment]
`gUnk_` is easier to search on than just `g`.

**Comment by PikalaxALT** [comment]
Agree. Gen 3 nomenclature works there just as well as it would here. Case closed.

**Comment by AsparagusEduardo** [comment]
> Agree. Gen 3 nomenclature works there just as well as it would here. Case closed.

Same.

**Comment by luckytyphlosion** [comment]
Re-opening because we need to decide on the naming for unknown static/global variables in overlays. Do we do `gUnk_ov80_0223F900` or `gOv66_0223F900`?

**Comment by adrienntindall** [comment]
> Re-opening because we need to decide on the naming for unknown static/global variables in overlays. Do we do `gUnk_ov80_0223F900` or `gOv66_0223F900`?

Yes that's fine, they'll have a g prefix eventually anyways
