### ISSUE TITLE
Style: State machines should have constants defined for them to make them easier to modify

### ISSUE THREAD

**Issue by luckytyphlosion** [pret/pokeheartgold#222]
Useful grep command: `grep -Pzowr --include="*.c" --include="*.h" --exclude-dir="tools" --exclude-dir="sub" --exclude-dir="lib" --exclude-dir=".github" --exclude-dir="files" 'switch \([^{]+\n?[^{\n]*{(?:\s+//.*?\n)*\s*case (?:(?:0x[0-9a-f]+|[0-9])*\s*[&\*\+-/\|]*)+:.*?\n' | tr -d '\000'`

Unfortunately does not catch `switch` statements starting with `default:`, so a custom tool would need to be made

**Comment by luckytyphlosion** [comment]
Should also probably make unknown enums even if they're something like `SUB_02031780_UNK_STATE_0`

**Comment by PikalaxALT** [comment]
Not entirely necessary for all state machines, but for the uber important ones (field loop, script processor, etc.), and for any SMs reached going forward, this should be implemented. Low priority.

**Comment by tgsm** [comment]
> Not entirely necessary for all state machines, but for the uber important ones (field loop, script processor, etc.), and for any SMs reached going forward, this should be implemented. Low priority.

I agree with this.

**Comment by adrienntindall** [comment]
I agree with low priority and personally, I only care about the state constants when the functions get documented. Will point out when documented state machines need their constants going forward etc and everyone else should do the same.
