### ISSUE TITLE
Decide on name-formatting for move constants

### ISSUE THREAD

**Issue by lhearachel** [pret/pokeheartgold#252]
Modern canonical names vs gen4 names, e.g.:

```c
#define MOVE_VISE_GRIP
#define MOVE_FEINT_ATTACK
#define MOVE_SMOKESCREEN
#define MOVE_SMELLING_SALTS
```

vs.

```c
#define MOVE_VICE_GRIP
#define MOVE_FAINT_ATTACK
#define MOVE_SMOKE_SCREEN
#define MOVE_SMELLING_SALT
```

[Canonical list of modified moves.](https://bulbapedia.bulbagarden.net/wiki/List_of_modified_moves#Between_generations_15)

**Comment by lhearachel** [comment]
For additional context, `pokeemerald` uses a mix (`MOVE_THUNDER_PUNCH` vs. `MOVE_VICE_GRIP`).

**Comment by lhearachel** [comment]
Just as a note, the repo currently uses modern names in the const definitions: https://github.com/pret/pokeheartgold/blob/feacd38986656e8a5051726566fd2814191c3c6a/include/constants/moves.h#L15

**Comment by Kurausukun** [comment]
One vote for canonical/gen 4

**Comment by mid-kid** [comment]
Another vote for gen4

**Comment by adrienntindall** [comment]
I like whichever one the bottom is

**Comment by lhearachel** [comment]
Vote for canonical

**Comment by lhearachel** [comment]
> I like whichever one the bottom is

Bottom is gen4.

**Comment by cbt6** [comment]
Prefer gen 4 names.

> Just as a note, the repo currently uses modern names in the const definitions:

Sounds like a bug to me.
